-
  branches:
    only:
    - nuget
    
  before_build:
    - dotnet restore Ghpr.MSTestV2/Ghpr.MSTestV2.sln

  build_script: 
    - dotnet build Ghpr.MSTestV2/Ghpr.MSTestV2.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - dotnet pack -c Release "Ghpr.MSTestV2/Ghpr.MSTestV2/Ghpr.MSTestV2.csproj" /p:NuspecFile="Ghpr.MSTestV2.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 
  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
        
-
  branches:
    except:
    - nuget
    
  before_build:
    - dotnet restore Ghpr.MSTestV2/Ghpr.MSTestV2.sln

  build_script: 
    - dotnet build Ghpr.MSTestV2/Ghpr.MSTestV2.sln /p:Configuration=Release /t:Rebuild

  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
